version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 381408
       MYSQL_DATABASE: my_db
       MYSQL_USER: tmh01
       MYSQL_PASSWORD: 381408

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "9000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: tmh
       WORDPRESS_DB_PASSWORD: 381408
       WORDPRESS_DB_NAME: db_wp
volumes:
    db_data: {}
